services:
  - type: web
    name: rsshub-sc05
    env: node
    plan: free
    buildCommand: |
      npm install
      npm install puppeteer
      npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

      # Puppeteer fix for TikTok
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.cache/puppeteer/chrome/linux-136/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"

      # Nitter instances (for Twitter feeds)
      - key: NITTER_INSTANCES
        value: '["https://nitter.poast.org","https://nitter.salastil.com"]'

      # Instagram cookie (needed for IG feeds)
      # ⚠ Replace YOUR_COOKIE_HERE with your real cookie string
      - key: INSTAGRAM_COOKIE
        value: sessionid=2890202863%3Az6USlAhgsT2oQp%3A25%3AAYjqhZjcd3BzWFBkHHeiA5H2T_whbVG01bn-4wGtEg; csrftoken=HZNTAnI5spOGeKItyLMpBrfdaeWA5FXn; ds_user_id=2890202863; mid=aFktIwALAAHsK00cPyxBXZcnp70O; rur=CCO,2890202863,1789354352:01fe40d9efa389111c57a2cb457429ce1da2721b7375c44bccd3618b1ebd7fb003f8548c
